# 测试环境专属配置
spring:
  profiles: test

# 测试环境关闭JWT拦截器
jwt:
  interceptor:
    enable: true

# 测试环境MyBatis-Plus打印SQL（可选）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
